# Generated by Django 2.2.4 on 2019-08-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='started_date',
            field=models.DateField(null=True),
        ),
    ]
